foxglove_bridge_ccu:
  ros__parameters:
    address: 0.0.0.0
    asset_uri_allowlist:
    - ^package://(?:\w+/)*\w+\..*$
    capabilities:
    - clientPublish
    - connectionGraph
    - services
    - assets
    certfile: ''
    client_topic_whitelist:
    - .*
    include_hidden: false
    keyfile: ''
    max_qos_depth: 100
    min_qos_depth: 1
    param_whitelist:
    - .*
    port: 8765
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    send_buffer_limit: 50000000
    service_whitelist:
    - .*
    tls: false
    topic_whitelist:
    - .*
    use_compression: true
