#!/usr/bin/env python
# Software License Agreement (BSD License)
#
# Copyright (c) 2008, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of the Willow Garage nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

## A basic node to monitor diagnostics for expected status

import roslib; roslib.load_manifest('runtime_monitor')

import sys, time
import rospy
from robot_msgs.msg import DiagnosticMessage

NAME = 'runtime_test'

latest_messages = {}
test_name = 'uninitialized'
package = 'uninitialized'
last_runtime = rospy.rostime.get_time()

def status_to_map(status):
    str_map = {}
    for s in status.strings:
        str_map[s.label] = s.value;
    for val in status.values:
        str_map[val.label] = val.value;
    str_map["name"]= status.name
    str_map["message"] = status.message
    return str_map
    
def analyze(package, test_impl, params):
    # run the test
    return test_impl.test(latest_messages, params)

def error_response(error):
    rospy.logerr( "Error: %s"% error)

def warning_response(warning):
    rospy.logwarn("Warning: %s"% warning)


def callback(message, args):
    for s in message.status:
        latest_messages[s.name] = status_to_map(s)
    sys.stdout.flush()
    execute_test(args)

def execute_test(args):
    global last_runtime
    time_step = rospy.rostime.get_time() - last_runtime
    if 1.0 /time_step > options.max_freq:
        return
    else:
        last_runtime = rospy.rostime.get_time()
    
    test_impl, params = args
    results = analyze(package, test_impl, params)

    if 'error' in results:
        for err in results['error']:
            error_response(err)
    
    if 'warn' in results:
        for warn in results['warn']:
            warning_response(warn)

    
def runtime_test(package, test_name):
    # retrieve the test implementation
    roslib.load_manifest(package)
    __import__("%s.%s"%(package, test_name))
    try:
        pypkg = sys.modules[package]
    except KeyError:
        print >> sys.stderr, "ERROR: cannot locate test package %s"%package
        rospy.logerr("cannot locate test package %s"%package)
        sys.exit(1)
    test_impl = getattr(pypkg, test_name)    

    # must be inited before reading parameters
    rospy.init_node(NAME, anonymous=True)


    # get it's parameters
    params = rospy.get_param("~")

    rospy.Subscriber("/diagnostics", DiagnosticMessage, callback, (test_impl, params))

    while not rospy.is_shutdown():
        if rospy.rostime.get_time() - last_runtime > options.min_freq:
            time.sleep(0.25/options.min_freq)
        else:
            execute_test((test_impl, params))
        
if __name__ == '__main__': 
    from optparse import OptionParser
    parser = OptionParser(usage="usage: %prog [options]", prog='runtime_test')
    parser.add_option("--test", metavar="TEST_NAME",
                      dest="test_name", default='', 
                      type="string", help="test name")
    parser.add_option("--package", metavar="ROS_PACKAGE",
                      dest="package", default='runtime_monitor', 
                      type="string", help="package test is in")
    parser.add_option("--min_freq", metavar="min_frequency",
                      dest="min_freq", default='0.5', 
                      type="float", help="Minimum Execution Frequency(Hz)")
    parser.add_option("--max_freq", metavar="max_frequency",
                      dest="max_freq", default='1.0', 
                      type="float", help="Maximum Execution Frequency(Hz)")

    options, args = parser.parse_args()


    
    # expected or default
    package = options.package 
    
    if options.test_name:
        test_name = options.test_name 
    else:
        parser.error("you must give me a test to run")

    try:
        runtime_test(package, options.test_name)
    except KeyboardInterrupt, e:
        pass
    print "exiting"
