<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>diagnostic_topic_monitor</name>
  <version>1.0.0</version>
  <description>Generic functions to monitor the health of ROS topics.</description>

  <maintainer email="ingo.luetkebohle@de.bosch.com">Ingo Lütkebohle</maintainer>
  <maintainer email="Christian.Henkel2@de.bosch.com">Christian Henkel</maintainer>
  
  <license>BSD-3-Clause</license>

  <url type="website">https://index.ros.org/p/diagnostic_topic_monitor/</url>

  <author email="ingo.luetkebohle@de.bosch.com">Ingo Lütkebohle</author>
  <author email="tejas.kumarshastha@de.bosch.com">Tejas Kumar Shastha</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>diagnostic_msgs</depend>
  <depend>diagnostic_updater</depend>
  <depend>rclcpp_components</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>statistics_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3-ntplib</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>sensor_msgs</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
