name: Test diagnostics on windows and macos
on:
  pull_request:
  push:
    branches:
      - ros2-kilted
  schedule:
    # Run every week at 20:00 on Sunday
    - cron: "0 20 * * 0"

jobs:
  build_and_test:
    name: ${{ matrix.package }} on ${{ matrix.os }} under ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        package: [
            diagnostic_aggregator,
            diagnostic_common_diagnostics,
            diagnostic_remote_logging,
            diagnostic_updater,
            self_test,
          ]
        distro: [rolling]
        # According to https://github.com/ros-tooling/action-ros-ci/blob/eed42df3e61c71e19310bcb06078bc63f629c59c/.github/workflows/test.yml#L70, only windows-2019 is supported.
        os: [
          # macOS-latest,
          windows-2019
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@master
        with:
          target-ros2-distro: ${{ matrix.distro }}
          package-name: ${{ matrix.package }}
