name: Test diagnostics
on:
  pull_request:
  push:
    branches:
      - ros2
  schedule:
    # Run every week at 20:00 on Sunday
    - cron: "0 20 * * 0"

jobs:
  ros_distro_from_branch_name:
    runs-on: ubuntu-latest
    outputs:
      distro: ${{ steps.set-distro.outputs.distro }}
    steps:
      - name: Set ROS distro from branch name
        id: set-distro
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "This is a PR. Getting branch name from head ref."
            branch_name="${{ github.event.pull_request.head.ref }}"
          else
            echo "This is a push. Getting branch name from GITHUB_REF."
            branch_name="${GITHUB_REF##*/}"
          fi
          echo "> Branch name is: ${branch_name}"

          if [[ "${branch_name}" == *"ros2"* ]]; then
            distro="rolling"
          elif [[ "${branch_name}" == *"ros2-humble"* ]]; then
            distro="humble"
          elif [[ "${branch_name}" == *"ros2-jazzy"* ]]; then
            distro="jazzy"
          elif [[ "${branch_name}" == *"ros2-kilted"* ]]; then
            distro="kilted"
          else
            echo "! Unknown branch for determining ROS distro: ${GITHUB_REF##*/}"
            exit 1
          fi
          echo "> Determined ROS distro to be: ${distro}!"
          echo "distro=$distro" >> $GITHUB_OUTPUT
  build_and_test:
    name: ${{ matrix.package }} on under ${{ matrix.distro }}
    needs: ros_distro_from_branch_name
    strategy:
      fail-fast: false
      matrix:
        package: [
            diagnostic_aggregator,
            diagnostic_common_diagnostics,
            diagnostic_remote_logging,
            diagnostic_updater,
            self_test,
          ]
        include:
          - distro: ${{ needs.ros_distro_from_branch_name.outputs.distro }}
            os: 24.04
    runs-on: ubuntu-latest
    container: ubuntu:${{ matrix.os }}
    steps:
      - uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@main
        with:
          target-ros2-distro: ${{ matrix.distro }}
          package-name: ${{ matrix.package }}
          # vcs-repo-file-url: |
          #   https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
